### ISSUE TITLE
bug: copy button not working when clicked

### ISSUE THREAD

**Issue by toufiqfarhan0** [code100x/daily-code#509] opened 2024-08-04 07:12 UTC
Copy button is not working when clicked and not coping the code 

https://github.com/user-attachments/assets/abb8d155-b5c0-4da7-9333-d89e8cbaf01e

Expected behavior:
Copy the code when copy button is clicked

**Comment by iharsh02** [comment] 2024-08-04 10:01
its working you can check by pasting somewhere

**Comment by ramnaresh8** [comment] 2024-08-04 21:29
yes, the issue is the animation isn't working but it is getting copied, check your clipboard using win + v if on windows or try pasting in case of mac

**Comment by devsargam** [comment] 2024-08-05 05:34
@ramnaresh8 do you want to work on this?

**Comment by ramnaresh8** [comment] 2024-08-05 06:44
> @ramnaresh8 do you want to work on this?

Yes, please assign it to me.

**Comment by toffee-k21** [comment] 2024-08-05 08:40
it is already solved in the current repo

**Comment by DivyeshPatel007** [comment] 2024-08-05 11:21
@devsargam  can you assign me this issue  i have done with better UI

**Comment by toufiqfarhan0** [comment] 2024-08-05 14:39
Is it solved?

**Comment by DivyeshPatel007** [comment] 2024-08-05 14:41
Yes

**Comment by toufiqfarhan0** [comment] 2024-08-05 17:31
> @devsargam I would like to work on this.

this is solved in current repo

**Comment by toufiqfarhan0** [comment] 2024-08-05 17:32
> @ramnaresh8 do you want to work on this?



this issue has be solved in current repo but not updated.

**Comment by ramnaresh8** [comment] 2024-08-05 19:21
> > @ramnaresh8 do you want to work on this?
> 
> this issue has be solved in current repo but not updated.

Okay,

**Closed** 2024-08-09 11:55 UTC
Labels: bug
