### ISSUE TITLE
Navbar bonked in light mode

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#35] opened 2024-02-01 21:55 UTC
<img width="1682" alt="Screenshot 2024-02-01 at 10 55 05 PM" src="https://github.com/code100x/daily-code/assets/8079861/6f544bd2-602d-4feb-91ba-e874fd451026">

**Comment by pvcodes** [comment] 2024-02-11 17:17
**REQUEST:** For resolved issues, please mark them closed. I was looking for some good issues to contribute but most of them are either PRed or merged, but the issue is still marked open. in [cms](https://github.com/code100x/cms) repo too.
PEACE!

**Closed** 2024-02-11 17:19 UTC
