### ISSUE TITLE
Breadcrumb issue

### ISSUE THREAD

**Issue by shahrukhshaikh19** [code100x/daily-code#30] opened 2024-02-01 10:35 UTC
When we clicks on breadcrumb link it's redirecting to 404 page.

**Comment by SujithThirumalaisamy** [comment] 2024-04-10 06:47
Can you please specify any further details like screenshorts or some specific place where it occur? Cannot reproduce this...

**Comment by nischal-shetty2** [comment] 2024-04-16 16:07
There are mo breadcrumbs in daily code I think he mistook cms repo @hkirat can you close this

**Closed** 2024-08-09 11:53 UTC
