### ISSUE TITLE
bug: Two Wrapper Components are of not same size

### ISSUE THREAD

**Issue by Pulkitnj** [code100x/daily-code#389] opened 2024-05-05 18:28 UTC
**Describe the bug**
These two components displayed below are of a different size compared to all the others.

**To Reproduce**
1. Inspect the CSS styling applied to the components that appear to be of different size.
2. Check for any specific width or height properties that might be causing the discrepancy.
3. Look for differences in padding or margin settings compared to the other components.

**Expected behavior**
All components should have consistent styling in terms of size, padding, and margin. Adjust the CSS properties of the problematic components to match those of the others, ensuring uniform appearance across the board.

**Screenshots or GIFs**
<img width="1440" alt="Screenshot 2024-05-05 at 11 32 08 PM" src="https://github.com/code100x/daily-code/assets/114797446/3b148fdf-8b01-426f-b767-851ba58957cd">
<img width="1440" alt="Screenshot 2024-05-05 at 11 31 30 PM" src="https://github.com/code100x/daily-code/assets/114797446/47bc3c12-1c07-4708-828f-e8289796f0da">

**Comment by kushaltolia** [comment] 2024-05-06 08:03
cna this be assigned to me

**Comment by hxdy-1** [comment] 2024-05-06 10:20
@kushaltolia don't wait for the assignment since it's a small issue, fix it and raise the PR. Also, I am unable to reproduce it on local but can see the bug on the live.

**Closed** 2024-08-09 11:54 UTC
Labels: bug
