### ISSUE TITLE
Add more space on the top 

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#584] opened 2024-08-27 11:42 UTC
![Screenshot 2024-08-27 at 5 11 45 PM](https://github.com/user-attachments/assets/c912af50-18db-45ac-b9ce-e4d83f6a007b)

**Comment by Paribesh01** [comment] 2024-08-27 11:48
can i work on this

**Comment by ItsFlash10** [comment] 2024-08-27 12:36
I have fixed it in [this](#575 ) along with #573 PR and its merged already.
@hkirat please check this once as multiple issues are being created which are already have been catered in that PR :)
Thanks!
cc: @devsargam

**Comment by devsargam** [comment] 2024-08-27 12:51
@ItsFlash10 I think the issue is still there. Can u once show some screeenshots

**Comment by devsargam** [comment] 2024-08-27 12:58
Thanks @ItsFlash10. @hkirat already resolved when #573 got merged

**Closed by devsargam** 2024-08-27 12:58 UTC
Labels: enhancement
